### PR TITLE
feat(platform-ref): platform-ref-* adoptions

### PR DESCRIPTION
**Pull request by haarchri**
### Description of your changes
- remove .up folder, switch examples and doc to top-level
- adoption for platform-ref-* providerconfigs 
- use e2e ci from template
- usages

Fixes #

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### CODE REVIEW

**Comment by haarchri** [comment]
need to merge this pr - that the e2e workflow will be updated on main branch

**Review by humoflife — APPROVED** [review]

**Comment by humoflife** [comment]
Tested and merged.

**Pull request merged**
